sneakHidesName: true # should we hide a player's name if they're sneaking?
sneakHideDistance: 10 # and if so, at what distance should it be hidden?
showNameWhenSprinting: false # should names of players who are sprinting be shown even through walls?